#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from texter4.ui on Tue Apr 15 17:09:47 2014
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TextSorterDialog(object):
    def setupUi(self, TextSorterDialog):
        TextSorterDialog.setObjectName(_fromUtf8("TextSorterDialog"))
        TextSorterDialog.resize(588, 584)
        self.horizontalLayout = QtGui.QHBoxLayout(TextSorterDialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.text_list = QtGui.QListView(TextSorterDialog)
        self.text_list.setMinimumSize(QtCore.QSize(0, 576))
        self.text_list.setMaximumSize(QtCore.QSize(16777215, 576))
        self.text_list.setObjectName(_fromUtf8("text_list"))
        self.horizontalLayout.addWidget(self.text_list)
        self.kbuttongroup = KButtonGroup(TextSorterDialog)
        self.kbuttongroup.setObjectName(_fromUtf8("kbuttongroup"))
        self.verticalLayout = QtGui.QVBoxLayout(self.kbuttongroup)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.remove_button = KPushButton(self.kbuttongroup)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-delete"))
        self.remove_button.setIcon(icon)
        self.remove_button.setObjectName(_fromUtf8("remove_button"))
        self.verticalLayout.addWidget(self.remove_button)
        self.move_up_button = KArrowButton(self.kbuttongroup)
        self.move_up_button.setObjectName(_fromUtf8("move_up_button"))
        self.verticalLayout.addWidget(self.move_up_button)
        self.move_down_button = KArrowButton(self.kbuttongroup)
        self.move_down_button.setProperty("arrowType", 2)
        self.move_down_button.setObjectName(_fromUtf8("move_down_button"))
        self.verticalLayout.addWidget(self.move_down_button)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.kbuttongroup)
        self.text_preview = KRichTextWidget(TextSorterDialog)
        self.text_preview.setMinimumSize(QtCore.QSize(0, 576))
        self.text_preview.setMaximumSize(QtCore.QSize(16777215, 576))
        self.text_preview.setObjectName(_fromUtf8("text_preview"))
        self.horizontalLayout.addWidget(self.text_preview)

        self.retranslateUi(TextSorterDialog)
        QtCore.QMetaObject.connectSlotsByName(TextSorterDialog)

    def retranslateUi(self, TextSorterDialog):
        TextSorterDialog.setWindowTitle(kdecore.i18n(_fromUtf8("Form")))
        self.remove_button.setText(kdecore.i18n(_fromUtf8("Remove")))

from PyKDE4.kdeui import KButtonGroup, KArrowButton, KPushButton, KRichTextWidget
