# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'texter2.ui'
#
# Created: Sat Apr 12 14:47:10 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1554, 658)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(169, 167, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/texter/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.live_text = KRichTextWidget(self.centralwidget)
        self.live_text.setMinimumSize(QtCore.QSize(768, 576))
        self.live_text.setMaximumSize(QtCore.QSize(768, 576))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(22)
        self.live_text.setFont(font)
        self.live_text.setStatusTip(_fromUtf8(""))
        self.live_text.setWhatsThis(_fromUtf8(""))
        self.live_text.setAutoFillBackground(False)
        self.live_text.setAcceptRichText(True)
        self.live_text.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.live_text.setObjectName(_fromUtf8("live_text"))
        self.verticalLayout.addWidget(self.live_text)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.clear_live_button = KPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.clear_live_button.setIcon(icon)
        self.clear_live_button.setObjectName(_fromUtf8("clear_live_button"))
        self.horizontalLayout_2.addWidget(self.clear_live_button)
        self.live_save_button = KPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.live_save_button.setIcon(icon)
        self.live_save_button.setObjectName(_fromUtf8("live_save_button"))
        self.horizontalLayout_2.addWidget(self.live_save_button)
        self.live_color = KColorButton(self.centralwidget)
        self.live_color.setObjectName(_fromUtf8("live_color"))
        self.horizontalLayout_2.addWidget(self.live_color)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.preview_text = KRichTextWidget(self.centralwidget)
        self.preview_text.setMinimumSize(QtCore.QSize(400, 576))
        self.preview_text.setMaximumSize(QtCore.QSize(768, 576))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(22)
        self.preview_text.setFont(font)
        self.preview_text.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.preview_text.setAutoFillBackground(False)
        self.preview_text.setFrameShape(QtGui.QFrame.StyledPanel)
        self.preview_text.setAcceptRichText(True)
        self.preview_text.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.preview_text.setObjectName(_fromUtf8("preview_text"))
        self.verticalLayout_2.addWidget(self.preview_text)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.clear_preview_button = KPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.clear_preview_button.setIcon(icon)
        self.clear_preview_button.setObjectName(_fromUtf8("clear_preview_button"))
        self.horizontalLayout.addWidget(self.clear_preview_button)
        self.publish_button = KPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.publish_button.setIcon(icon)
        self.publish_button.setObjectName(_fromUtf8("publish_button"))
        self.horizontalLayout.addWidget(self.publish_button)
        self.previous_button = KPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-skip-backward"))
        self.previous_button.setIcon(icon)
        self.previous_button.setObjectName(_fromUtf8("previous_button"))
        self.horizontalLayout.addWidget(self.previous_button)
        self.next_button = KPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-skip-forward"))
        self.next_button.setIcon(icon)
        self.next_button.setObjectName(_fromUtf8("next_button"))
        self.horizontalLayout.addWidget(self.next_button)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.preview_color = KColorButton(self.centralwidget)
        self.preview_color.setObjectName(_fromUtf8("preview_color"))
        self.horizontalLayout.addWidget(self.preview_color)
        self.preview_save_button = KPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.preview_save_button.setIcon(icon)
        self.preview_save_button.setObjectName(_fromUtf8("preview_save_button"))
        self.horizontalLayout.addWidget(self.preview_save_button)
        self.text_open_button = KPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.text_open_button.setIcon(icon)
        self.text_open_button.setObjectName(_fromUtf8("text_open_button"))
        self.horizontalLayout.addWidget(self.text_open_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.live_text, self.preview_text)
        MainWindow.setTabOrder(self.preview_text, self.publish_button)
        MainWindow.setTabOrder(self.publish_button, self.clear_preview_button)
        MainWindow.setTabOrder(self.clear_preview_button, self.clear_live_button)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "4.48 Texter", None))
        self.live_text.setToolTip(_translate("MainWindow", "live text", "tooltip1"))
        self.clear_live_button.setToolTip(_translate("MainWindow", "clear live text", None))
        self.clear_live_button.setShortcut(_translate("MainWindow", "F1", None))
        self.live_color.setText(_translate("MainWindow", "background", None))
        self.preview_text.setToolTip(_translate("MainWindow", "preview text", None))
        self.clear_preview_button.setToolTip(_translate("MainWindow", "clear preview text", None))
        self.clear_preview_button.setStatusTip(_translate("MainWindow", "status tip2", None))
        self.clear_preview_button.setWhatsThis(_translate("MainWindow", "whatsthis2", None))
        self.clear_preview_button.setShortcut(_translate("MainWindow", "F2", None))
        self.publish_button.setToolTip(_translate("MainWindow", "go live with text", None))
        self.publish_button.setShortcut(_translate("MainWindow", "F4", None))
        self.preview_color.setText(_translate("MainWindow", "background", None))

from PyKDE4.kdeui import KColorButton, KPushButton, KRichTextWidget
import texter_rc
